language: r
cache: packages
sudo: required
warnings_are_errors: false

before_install:
  - sudo apt-get install r-cran-rmpi

notifications:
  email:
    on_success: change
    on_failure: always

after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
